# Generated by Django 3.0.8 on 2020-08-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20200805_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='github',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
