# Generated by Django 3.0.8 on 2020-07-30 21:34

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0006_auto_20200727_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_me_headshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_me_summary',
            field=wagtail.core.fields.RichTextField(default='stuff'),
            preserve_default=False,
        ),
    ]
