# Generated by Django 3.0.8 on 2020-07-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200723_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='second_title',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='subtitle',
        ),
    ]
