# Generated by Django 3.0.8 on 2020-07-23 23:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('blog', '0003_auto_20200723_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='blog_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='blog_post',
            field=wagtail.core.fields.RichTextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpage',
            name='blog_subtitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
